name: SolarsCombatRolePlayPlugin
main: net.solar_studios.CombatManagerPlugin
version: 0.0.1
author: Logan C Hobson
api-version: 1.21.3
commands:
  createcombat:
    description: Create a new combat.
  joincombat:
    description: Join an existing combat.
  startcombat:
    description: Start combat.
  damage:
    description: Deal damage to a target.
  leavecombat:
    description: Removes player from their joined combat.
  lockcombat:
    description: Locks players from joining the combat.
  removefromcombat:
      description: Removes a specific player from the combat.