name: SolarsCombatRolePlayPlugin
main: net.solar_studios.CombatManagerPlugin
version: 0.0.1
author: Logan C Hobson
api-version: 1.21.3
commands:
  createcombat:
    description: Create a new combat.
  joincombat:
    description: Join an existing combat.
  startcombat:
    description: Start combat.
  damage:
    description: Deal damage to a target.